"""Navigation package — Sprint 4 deliverable for Lumen.

Public API:
- NavigationTaskManager: the orchestrator the FSM / WebSocket layer talks to.
- NavigationContext, Waypoint, WaypointStatus: data types (mostly for tests
  and for the frame-processing layer in later parts).
- LandmarkDetector: per-frame detection consumer (Part 2).
- parse_waypoint, normalize_phrase, is_cancellation_phrase, is_arrival_phrase:
  text helpers exposed for tests and for the WebSocket layer's transcription
  routing.
- landmark_map.resolve / is_known: alias-to-COCO-class lookup (Part 2).
"""

from .context import (
    NavigationContext,
    Waypoint,
    WaypointStatus,
    DETECTION_WINDOW,
    DETECTION_MIN_HITS,
)
from .detector import (
    LandmarkDetector,
    CONFIDENCE_THRESHOLD,
    LANDMARK_DETECTION_TIMEOUT_SECONDS,
    DISAMBIGUATION_TIMEOUT_SECONDS,
    OBSTACLE_WARNING_COOLDOWN_SECONDS,
    MAX_OBSTACLE_ESCALATION_LEVEL,
)
from .landmark_map import (
    resolve as resolve_landmark,
    is_known as is_known_landmark,
    snapshot_dict as landmark_snapshot,
    LANDMARK_ALIASES,
    COCO_CLASSES,
    FUZZY_THRESHOLD,
)
from .obstacle_map import (
    is_obstacle,
    is_person,
    is_small_object,
    obstacle_priority,
    display_name as obstacle_display_name,
    OBSTACLE_CLASSES,
    PERSON_CLASSES,
    LARGE_OBSTACLES,
    SMALL_OBSTACLES,
    SMALL_OBJECT_MIN_BBOX_AREA_RATIO,
)
from .manager import (
    NavigationTaskManager,
    create_navigation_session,
    WAYPOINT_PROMPT_TEXT,
    WAYPOINT_REPROMPT_TEXT,
    WAYPOINT_CONFIRMATION_TEMPLATE,
    WAYPOINT_CANCELLED_TEXT,
    WAYPOINT_TIMEOUT_TEXT,
    WAYPOINT_GIVEUP_TEXT,
    WAYPOINT_UNKNOWN_TEXT,
    WAYPOINT_PARTIAL_RECOGNITION_TEMPLATE,
    WAYPOINT_REACHED_TEMPLATE,
    NEXT_WAYPOINT_PROMPT_TEXT,
    DETECTION_TIMEOUT_TEXT,
    DISAMBIGUATION_PROMPT_TEMPLATE,
    DISAMBIGUATION_REPROMPT_TEXT,
    DISAMBIGUATION_CONFIRMATION_TEMPLATE,
    OBSTACLE_WARNING_LEVEL0_TEMPLATE,
    OBSTACLE_WARNING_LEVEL1_TEMPLATE,
    OBSTACLE_WARNING_LEVEL2_TEMPLATE,
    OBSTACLE_PERSON_LEVEL0_TEMPLATE,
    OBSTACLE_PERSON_LEVEL1_TEMPLATE,
    OBSTACLE_PERSON_LEVEL2_TEMPLATE,
    GUIDANCE_LOST_SIGHT_TEMPLATE,
    NAVIGATION_COMPLETE_TEXT,
    WHATS_NEXT_PROMPT_TEXT,
    COMPLETION_TIMEOUT_TEXT,
    ARRIVAL_CONFIRMATION_TEMPLATE,
    ARRIVAL_CONFIRMATION_NO_OBSERVATION_TEMPLATE,
    ARRIVAL_CONFIRMED_DECLINED_TEXT,
    WAYPOINT_PROMPT_TIMEOUT_SECONDS,
    MAX_WAYPOINT_REPROMPTS,
    MAX_DISAMBIGUATION_REPROMPTS,
)
from .parser import (
    parse_waypoint,
    normalize_phrase,
    is_cancellation_phrase,
    is_arrival_phrase,
    is_yes,
    is_no,
    is_done_phrase,
)
from .goal_map import (
    resolve_goal,
    is_known_goal,
    indicators_for,
    evaluate_arrival,
    arrival_phrase,
    GOAL_INDICATORS,
    GOAL_ALIASES,
)

__all__ = [
    "NavigationTaskManager",
    "NavigationContext",
    "Waypoint",
    "WaypointStatus",
    "DETECTION_WINDOW",
    "DETECTION_MIN_HITS",
    "LandmarkDetector",
    "CONFIDENCE_THRESHOLD",
    "LANDMARK_DETECTION_TIMEOUT_SECONDS",
    "DISAMBIGUATION_TIMEOUT_SECONDS",
    "OBSTACLE_WARNING_COOLDOWN_SECONDS",
    "MAX_OBSTACLE_ESCALATION_LEVEL",
    "resolve_landmark",
    "is_known_landmark",
    "landmark_snapshot",
    "LANDMARK_ALIASES",
    "COCO_CLASSES",
    "FUZZY_THRESHOLD",
    "is_obstacle",
    "is_person",
    "is_small_object",
    "obstacle_priority",
    "obstacle_display_name",
    "OBSTACLE_CLASSES",
    "PERSON_CLASSES",
    "LARGE_OBSTACLES",
    "SMALL_OBSTACLES",
    "SMALL_OBJECT_MIN_BBOX_AREA_RATIO",
    "parse_waypoint",
    "normalize_phrase",
    "is_cancellation_phrase",
    "is_arrival_phrase",
    "is_yes",
    "is_no",
    "is_done_phrase",
    "create_navigation_session",
    "WAYPOINT_PROMPT_TEXT",
    "WAYPOINT_REPROMPT_TEXT",
    "WAYPOINT_CONFIRMATION_TEMPLATE",
    "WAYPOINT_CANCELLED_TEXT",
    "WAYPOINT_TIMEOUT_TEXT",
    "WAYPOINT_GIVEUP_TEXT",
    "WAYPOINT_UNKNOWN_TEXT",
    "WAYPOINT_PARTIAL_RECOGNITION_TEMPLATE",
    "WAYPOINT_REACHED_TEMPLATE",
    "NEXT_WAYPOINT_PROMPT_TEXT",
    "DETECTION_TIMEOUT_TEXT",
    "DISAMBIGUATION_PROMPT_TEMPLATE",
    "DISAMBIGUATION_REPROMPT_TEXT",
    "DISAMBIGUATION_CONFIRMATION_TEMPLATE",
    "OBSTACLE_WARNING_LEVEL0_TEMPLATE",
    "OBSTACLE_WARNING_LEVEL1_TEMPLATE",
    "OBSTACLE_WARNING_LEVEL2_TEMPLATE",
    "OBSTACLE_PERSON_LEVEL0_TEMPLATE",
    "OBSTACLE_PERSON_LEVEL1_TEMPLATE",
    "OBSTACLE_PERSON_LEVEL2_TEMPLATE",
    "GUIDANCE_LOST_SIGHT_TEMPLATE",
    "NAVIGATION_COMPLETE_TEXT",
    "WHATS_NEXT_PROMPT_TEXT",
    "COMPLETION_TIMEOUT_TEXT",
    "ARRIVAL_CONFIRMATION_TEMPLATE",
    "ARRIVAL_CONFIRMATION_NO_OBSERVATION_TEMPLATE",
    "ARRIVAL_CONFIRMED_DECLINED_TEXT",
    "WAYPOINT_PROMPT_TIMEOUT_SECONDS",
    "MAX_WAYPOINT_REPROMPTS",
    "MAX_DISAMBIGUATION_REPROMPTS",
    "resolve_goal",
    "is_known_goal",
    "indicators_for",
    "evaluate_arrival",
    "arrival_phrase",
    "GOAL_INDICATORS",
    "GOAL_ALIASES",
]
